version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre-build
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post-build
      
artifacts:
  files:
    - target/my-todo-app-0.0.1-SNAPSHOT.jar
